### ISSUE TITLE
HTTP 404 from OCA repository API after fresh install

### ISSUE THREAD

**Issue by foxbike** [THCLab/oca-repository#17]
After a fresh install with docker-compose, calls to the OCA-repository API always return a http 404 error.

**Comment by mitfik** [comment]
Could you be more verbose on which requests you received `404` ? 

`404` is returned when you trying to query item which does not exist, are you sure you uploaded objects which you are query?

**Comment by foxbike** [comment]
Fresh new Ubuntu 18.04. Fresh clone of this repository. Execute instructions on ReadMe.md page. Run with docker-compose up. Try to upload a oca bundle (zip). I get 404. I thing i get 404 on all routes.

**Comment by blelump** [comment]
@foxbike 

can you elaborate on how you upload the bundle ?

**Comment by mitfik** [comment]
Tried on the recent images and all seems to work fine:

```
curl -X 'POST' \
  'http://localhost:9292/api/v0.1/namespaces/hcf/schemas' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@E2oRZ5zEKxTfTdECW-v2Q7bM_H0OD0ko7IcCwdo_u9co.zip;type=application/zip'
{"success":true,"SAI":"E2oRZ5zEKxTfTdECW-v2Q7bM_H0OD0ko7IcCwdo_u9co","path":"http://localhost:9292/api/v0.1/namespaces/hcf/schemas/E2oRZ5zEKxTfTdECW-v2Q7bM_H0OD0ko7IcCwdo_u9co"}%   
```

@foxbike I think we need more input from your side what you are doing, step by step to better understand where the issue could be.

**Comment by foxbike** [comment]
OK, it work on my mac. I have no 404 error. But on my fresh Ubuntu 18.04, i always receive 404 (even with a  curl call on api). Weird!
